version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/nuxt-frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/laravel-api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/python-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
